<!DOCTYPE html>
<html>
    <head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"><
		/script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    </head>
    <body style="background:grey; ">
      <nav class="navbar navbar-inverse">
		  <div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="/car/acc">Lamborghini</a>
				</div>
				<ul class="nav navbar-nav">
					<li class="active"><a href="/car/list"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
			  		<li><a href="/car/add"><span class="glyphicon glyphicon-plus-sign"></span>  New car</a></li>
				</ul>
		  </div>
		</nav> 
		<div>
		<center style="margin-top:10px" >
		   <font size="7"  face="Times New Roman" >Welcome to</font> 
		  <p style="font-size:26px; margin-bottom:30px;">Lamborghini's world</p>
		</center>
		
		<MARQUEE scrollamount="15">
			<div id="block1" class="col-md-2">
			<img src="/L1.jpg" class="img-responsive"> 
			</div>
			<div id="block2" class="col-md-2">
			<img src="/L2.jpg" class="img-responsive"> 
			</div>
			<div id="block3" class="col-md-2">
			<img src="/L4.jpg" class="img-responsive">
			</div>
			<div id="block4" class="col-md-2"> 
			<img src="/L6.jpg" class="img-responsive"> 
			</div>
			<div id="block5" class="col-md-2">
			<img src="/L9.jpg" class="img-responsive"> 
			</div>
		</MARQUEE>
		</div>
    </body>
</html>
