<!DOCTYPE html>
<html>
    <head>
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    </head>
    <body style="background:grey;">
       <nav class="navbar navbar-inverse">
                  <div class="container-fluid">
                                <div class="navbar-header">
                                        <a class="navbar-brand" href="/car/acc">Lamborghini</a>
                                </div>
                                <ul class="nav navbar-nav" >
                                        <li class="active"><a href="/car/list"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
                                        <li><a href="/car/add"><span class="glyphicon glyphicon-plus-sign"></span>  New car</a></li>
                                        <li class="dropdown">
                                                <a class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-pencil"></span>  Edit<span class="caret"></span></a>

                                                <ul class="dropdown-menu" style="width: 100%;background:black;">
                                                <?php foreach($Cars as $Car) {?>
                                                                                <form method="get" action='/car/edit/<?=$Car->id?>'>
                                                                                        <button class="container-fluid" style="width: 100%;" type="submit"><?=$Car->name ?></button>
                                                                                </form>
                                                <?php }?>
                                                </ul>
                                  </li>
                                </ul>
                  </div>
                </nav>
                <div>
        <div class="row" style="margin-top:-20px" >
                    <?php foreach($Cars as $Car) {?>
                                    <div id="block1" class="col-md-6" style="background:grey; border:1px solid black;">

                                            <div style="margin:20px; border:2px solid black;" class="col-sm-6 col-sm-push-3"><center><font size="5"><B>Owner : </B><?=$Car->name ?></font></center></div>




                                            <?php
                                            switch ($Car->img) {
                                                                case 1:
                                                                        echo"<img src='/L1.jpg' class='img-responsive img-rounded'/>";
                                                                        break;
                                                                case 2:
                                                                        echo"<img src='/L2.jpg' class='img-responsive img-rounded'/>";
                                                                        break;
                                                                case 3:
                                                                        echo"<img src='/L4.jpg' class='img-responsive img-rounded'/>";
																		break;
																case 4:
                                                                        echo"<img src='/L6.jpg' class='img-responsive img-rounded'/>";
                                                                        break;
                                                                case 5:
                                                                        echo"<img src='/L9.jpg' class='img-responsive img-rounded'/>";
                                                                        break;
                                                        }
                                            ?>

                                            <!--<img class="img-responsive img-thumbnail" src="Lambo1.jpg" style='width:100%;'> -->

                                        <form method="post" action='/car/delete/<?=$Car->id?>'>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                                <form method="get" action='/car/details/<?=$Car->id?>'>
                                                <button type="submit" class="btn btn-primary">Details</button>
                                        </form>

                                </div>
                     <?php }?>
          </div>
                 <form method="get" action='/car/add'>
                <button href="#" type="submit" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span>Add a new car</button>
         </form>

         </div>
    </body>
</html>
