<!DOCTYPE html>
<html>
    <head>
        <meta name="Lamborghini" content="width=device=width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    </head>
    <body>
        <div class="container">
            <form method="get" action='/Cars' style="margin:50px;">
                <div class="row">
                    <div id="block1" class="col-md-5" style="background:azure; border:1px solid blue;">
                        <h1>Lamborghini 1</h1>
                        <p>Sephora et son ordinateur.</p> 
                    </div> 
                    <div id="block2" class="col-md-5" style="background:#77B5FE; border:1px solid blue;">
                        <h2>Lamborghini 2</h2>
                        <p>Thomas et son ordinateur.</p>  
                    </div> 
                    <div id="block3" class="col-md-5" style="background:#318CE7; border:1px solid blue;">
                        <h3>Lamborghini 3</h3>
                        <p>Floriane et son ordinateur.</p>  
                    </div> 
                    <div id="block4" class="col-md-5" style="background:#2C75FF; border:1px solid blue;">
                        <h4>Lamborghini 4</h4>
                        <p>Karim et son ordinateur.</p>  
                    </div> 
                    <div id="block5" class="col-md-5" style="background:#357AB7; border:1px solid blue;">
                        <h5>Lamborghini 5</h5>
                        <p>Ammallan et les ordinateurs l'ecole.</p>  
                    </div> 
                    <div id="block6" class="col-md-5" style="background:#22427C; border:1px solid blue;">
                        <h6>Lamborghini 6</h6>
                        <p>Ivan et son ordinateur.</p>  
                    </div>         
                </div>
                <button type="submit" class="btn btn-default">Add a new car</button>
            </form>
            <button type="submit" action='/Delete' class="btn btn-default">Delete</button> 
        </div>  
    </body>
</html>
